-- טבלת בית נאמן - ילדים והוריהם מעל גיל 16
CREATE TABLE IF NOT EXISTS beit_neeman (
    id INT AUTO_INCREMENT PRIMARY KEY,
    family_name VARCHAR(255) NOT NULL COMMENT 'שם משפחה',
    child_name VARCHAR(255) NOT NULL COMMENT 'שם הילד',
    age INT COMMENT 'גיל',
    father_name VARCHAR(255) COMMENT 'שם האב',
    father_mobile VARCHAR(50) COMMENT 'נייד אב',
    mother_name VARCHAR(255) COMMENT 'שם האם',
    maiden_name VARCHAR(255) COMMENT 'לבית',
    mother_mobile VARCHAR(50) COMMENT 'נייד אם',
    address TEXT COMMENT 'כתובת',
    city VARCHAR(255) COMMENT 'עיר',
    gender ENUM('זכר', 'נקבה') COMMENT 'מין',
    child_id VARCHAR(20) COMMENT 'תעודת זהות',
    birth_day INT COMMENT 'יום',
    birth_month VARCHAR(50) COMMENT 'חודש עברי',
    birth_year INT COMMENT 'שנה עברית',
    study_place VARCHAR(255) COMMENT 'מקום לימודים',
    notes TEXT COMMENT 'הערות',
    status ENUM('רווק', 'מאורס', 'נשוי', 'גרוש') DEFAULT 'רווק' COMMENT 'סטטוס',
    child_record_id INT COMMENT 'קישור לרשומת ילד במאגר ילדים',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_family_name (family_name),
    INDEX idx_age (age),
    INDEX idx_status (status),
    INDEX idx_child_id (child_id),
    FOREIGN KEY (child_record_id) REFERENCES children(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
