-- טבלת נתמכים/משפחות לתמיכות
CREATE TABLE IF NOT EXISTS supports_families (
    id INT AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    station_name VARCHAR(255),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    id_number VARCHAR(20),
    city VARCHAR(100),
    street VARCHAR(100),
    phone VARCHAR(30),
    num_household INT,
    num_married_children INT,
    work_place1 VARCHAR(255),
    income1 DECIMAL(12,2),
    work_place2 VARCHAR(255),
    income2 DECIMAL(12,2),
    child_allowance DECIMAL(12,2),
    survivors_allowance DECIMAL(12,2),
    disability_allowance DECIMAL(12,2),
    income_support DECIMAL(12,2),
    income_supplement DECIMAL(12,2),
    rent_assistance DECIMAL(12,2),
    other_allowance_source VARCHAR(255),
    other_allowance_amount DECIMAL(12,2),
    housing_expense DECIMAL(12,2),
    tuition_expense DECIMAL(12,2),
    fixed_exception_expense DECIMAL(12,2),
    fixed_exception_detail VARCHAR(255),
    hardship_reason TEXT,
    notes TEXT,
    account_holder VARCHAR(100),
    bank VARCHAR(50),
    branch VARCHAR(50),
    account_number VARCHAR(50),
    support_requester VARCHAR(100),
    transaction_number VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
