-- יצירת טבלת people
CREATE TABLE IF NOT EXISTS people (
    id INT AUTO_INCREMENT PRIMARY KEY,
    amarchal VARCHAR(255),
    gizbar VARCHAR(255),
    software_id VARCHAR(255),
    donor_number VARCHAR(255),
    chatan_harar VARCHAR(255),
    family_name VARCHAR(255),
    first_name VARCHAR(255),
    name_for_mail VARCHAR(255),
    full_name VARCHAR(255),
    husband_id VARCHAR(20),
    wife_id VARCHAR(20),
    address VARCHAR(255),
    mail_to VARCHAR(255),
    neighborhood VARCHAR(255),
    floor VARCHAR(50),
    city VARCHAR(255),
    phone VARCHAR(50),
    husband_mobile VARCHAR(50),
    wife_name VARCHAR(255),
    wife_mobile VARCHAR(50),
    updated_email VARCHAR(255),
    husband_email VARCHAR(255),
    wife_email VARCHAR(255),
    receipts_to VARCHAR(255),
    alphon VARCHAR(255),
    send_messages VARCHAR(10),
    last_change DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
